### ISSUE TITLE
[arm] issues in the phones list

### ISSUE THREAD

**Issue by jhdeov** [kylebgorman/wikipron#298] opened 2020-12-29 07:42 UTC
Wonderful resource. 

There are some errors in the [phone](https://github.com/kylebgorman/wikipron/blob/master/data/phones/arm_e_phonetic.phones) list for the Armenian dialects. A lot of the errors got cleaned up since you last scraped them.

The way that the Wiktionary contributors for Armenian work is that they do the following:

1. They take the orthographic form like գրպան (transliteration is `<grban>`, pronunciation is [gərbɑn])
2. They manually the orthographic and rewrite it with Armenian letters in order to apply any phonological rules like schwa insertion: գրպան to գըրպան <gərban>
3. They then use [this](https://en.wiktionary.org/wiki/Module:hy-pronunciation) script to convert from the rewritten form (2) into the IPA for Eastern and Western Armenian
4. This means that the Western entries are almost all redundant and automatically derived from the Eastern entries. A lot of words actually include both IPA entries together.

For [Eastern](https://github.com/kylebgorman/wikipron/blob/master/data/phones/arm_e_phonetic.phones) (EA)
* You're right that the `<ա>` grapheme is /ɑ/. The script automatically converts the rewritten grapheme to [ɑ]. Some people had manually written the pronunciation entries and used non-IPA symbols like [a]. But they've mostly gotten cleaned up. A lot got cleaned before August. Then I personally scraped Wiktionary with another python package, found some overlooked [a]'s, and I cleaned them up too.
* Same issue with  `<ո>` actually being [ɔ] but sometimes incorrectly written as [o].
* Armenian doesn't have phonemic geminates. What you see is that the orthography has a sequence of identical consonants like փթթել `<pttel>` [pəttel]. The script automatically converts a sequence of identical segments into a geminate with the [ː] diacritic. So if the rewritten form is փըթթել `<pəttel>`, then the outputted pronunciation is [pət:el]. If the rewritten form is փըթել `<pətel>`, then the automatic output is [pətel]. IMO, it would make more sense if the automatic transcription was with doubled segments [pəttel] because Armenian lacks phonemic length. So all the consonants have a possible geminated/lengthened/doubled form. It might just be an accidental gap in the Wiktionary data that you don't have geminate t͡s: and others.
* The back fricatives are in free variation between velar and uvular, with more tendency towards uvular. The automatic transcription uses χ, so any [x] that you see is just an error (which I think also got cleaned up in around summer).
* What's the issue with missing tie-bars?

    * TODO: for future cleanup, missing tie-bars on segments like:
  <ց> [tʃʰ]
   <չ> [tsʰ]

For [Western](https://github.com/kylebgorman/wikipron/blob/master/data/phones/arm_w_phonetic.phones) (WA)
* Any [r] that you see is an error. The orthography has two rhotic graphemes ր ռ that are both pronounced the same as a flap. The trill is just someone manually writing it. That counts as an error and I think most of them got cleaned up on the WIktionary entries.
* Yup you're right about the mergers.
    * TODO: supposedly the following mergers have occurred in this dialect:
  aspirated              > aspirated 
  voiced                 > aspirated
  voiceless unaspirated  > voiced
* The W dialect also developing a devoicing rule for clusters of orthographic voice+voiceless consonants. The automatic transcription covers that though.

**Comment by kylebgorman** [comment] 2020-12-29 18:03
Thanks for the comments here. What are the action items we can take upstream (i.e., to Wiktionary itself) and/or to the phones lists to improve the data?

**Comment by jhdeov** [comment] 2020-12-29 18:10
Action items

1. Once you make an updated scrape of Wiktionary, you can redo the extract phone list
2. I can then use your list to fix all the errors on Wiktionary that still remain, e.g., I can remove all the <a> transcriptions
3. If there are any geminates that are missing in your phone list, I can search through wiktionary to make sure if they're accidentally absent (accidental gap) or if there's some human-errors in the transcriptions. I can then fix them
4. Once the actual Wiktionary is cleaned up based on your scrape, you can then re-do the Armenian scrape again and it should have a consistent phone list

So it's more about me fixing the Wiktionary entries to then make your scraping better.

**Comment by kylebgorman** [comment] 2020-12-29 18:12
Great, I'll ping this thread once I've updated this for Armenian. Will just
be a week or two. That'd be great, thanks.

**Comment by kylebgorman** [comment] 2020-12-31 16:21
Issue #301 is now closed by PR #302. You're welcome to take a stab at cleaning now.

**Comment by jhdeov** [comment] 2020-12-31 16:49
Thanks @kylebgorman. I'll look into coordinating this with the main Wiktionary editors that I know -- and potentially use your scrape to fix both the phone-list issue and the missing Western Armenian entries [issue](https://github.com/kylebgorman/wikipron/issues/301). 

Again, thanks a lot to your team for making this package in the first place.

**Comment by kylebgorman** [comment] 2020-12-31 16:51
Great. Anything you can do here can be incorporated into our SIGMORPHON
shared task (I will probably target Armenian again) long as it arrives in
the next month or two.

K

**Comment by jhdeov** [comment] 2020-12-31 16:59
Wonderful. One issue though. Because of widespread dispersion, there are often Wiktionary entries which have both a standard prescriptive pronunciation and a colloquial pronunciation, for example this word [երկրորդ](https://en.wiktionary.org/wiki/%D5%A5%D6%80%D5%AF%D6%80%D5%B8%D6%80%D5%A4):

(Eastern Armenian, standard) IPA(key): [jɛɾkˈɾɔɾtʰ], (colloquial) IPA(key): [jɛkˈɾɔɾtʰ]
(Western Armenian, standard) IPA(key): [ˈjɛɾɡɾɔɾtʰ], (colloquial) IPA(key): [ˈjɛɡɾɔɾtʰ]

It looks like your scraping correctly captures ALL these pronunciations. The Western data file includes both the standard and colloquial pronunciations. I'm not sure if that's a problem for you though. Because on the one hand you scrape the pronunciations. but on the other hand, the scraped data file doesn't tell you that one of the pronunciations is standard and the other colloquial.

**Comment by kylebgorman** [comment] 2020-12-31 17:02
If the HTML is conformant it should grab all of them unless the user
specifies a dialect; that is the intended behavior. We specify dialects
(eastern standard and western standard) for the "big scrape" data set
however, which is what we use for computational modeling purposes.

**Comment by jhdeov** [comment] 2020-12-31 17:04
I understand that point. But my point is about differentiating standard vs colloquial transcriptions. It seems that the HTML causes your code to retrieve both standard and colloquial Western even though you only select "Western Armenian, standard". My question is if that's a problem for you or not. And if it is a problem, would you recommend any changes to how the Armenian transcription entries are organized?

**Comment by kylebgorman** [comment] 2020-12-31 17:08
If that's so, file an issue, either here or upstream.

This seems like an upstream issue, there shouldn't be multiple
distinct-dialect/register pronunciations in the same entry. Rather they
ought to be laid out:

(Eastern Armenian, standard) IPA(key): [jɛɾkˈɾɔɾtʰ]
(Eastern Armenian, colloquial) IPA(key): [jɛkˈɾɔɾtʰ]
(Western Armenian, standard) IPA(key): [ˈjɛɾɡɾɔɾtʰ]
(Western Armenian, colloquial) IPA(key): [ˈjɛɡɾɔɾtʰ]

If this is generated by template it'd be a straightforward fix.

(Please try to keep distinct bugs separate. This does not seem germane to
the current bug.)

**Comment by jhdeov** [comment] 2020-12-31 17:09
Good point. Apologies.

**Comment by kylebgorman** [comment] 2020-12-31 17:13
If that's done we can scrape all 4 dialects separately, which would be nice.

**Comment by jhdeov** [comment] 2021-01-23 04:53
Hi. I managed to clean up the Armenian entries on Wiktionary. There's now around 14400 entries for Eastern, 14200 for Western. Their IPA has been fixed to remove the bad phones [o,u,x] and to fix the mixing digraphs on affricates. 

I rewrote your EA phone list on this [file](https://dpaste.com/2UK7Q6TEA), and your WA phone list on this [file](https://dpaste.com/AA2X4YP3P). I think you can close this issue, unless you recommend any other changes :D

**Comment by kylebgorman** [comment] 2021-01-23 16:40
Would you be willing to file those as a pull request so Aidan (or whoever)
can review them more closely?

(If you do so please remove the blank lines. I don't know what if anything
we do with blank lines.)

**Comment by jhdeov** [comment] 2021-01-24 00:28
Sure. [Here](https://github.com/kylebgorman/wikipron/pull/331) it is.

**Comment by kylebgorman** [comment] 2021-01-24 00:35
Thanks for this! Almost there.

**Closed** 2021-01-25 19:39 UTC
Labels: language support
